name: EOM Time Reporting Reminder

on:
  schedule:
    - cron: "0 10 * * *" # https://crontab.guru/#0_10_*_*_*

jobs:
  eom-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run EOM Check Script
        run: ./eom-check.sh

      - name: Send Slack Notification
        if: success()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "End of Month Time Reporting Reminder: Please ensure your time reports are up to date."
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
