name: Friday reminder

on:
  workflow_dispatch:
    inputs:
      channel:
        type: string
        description: Which channel would you like to send the message to?
        default: C07A7FY6YR1
  schedule:
    - cron: "0 14 * * 5" # at 14:00 (16:00 our time due to UTC) on every Friday (https://crontab.guru/#0_14_*_*_5)

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  friday-reminder:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read current index
        id: read_index
        run: |
          if [ -f .github/current_index.txt ]; then
            index=$(cat .github/current_index.txt)
          else
            index=0
          fi
          echo "index=$index" >> $GITHUB_ENV

      - name: Read message from freitag.json
        id: read_json
        run: |
          message=$(jq -r ".[$index].message // empty" .github/freitag.json)
          url=$(jq -r ".[$index].url // empty" .github/freitag.json)
          if [ -z "$message" ]; then
            index=$(jq 'length - 1' .github/freitag.json)
            message=$(jq -r ".[$index].message" .github/freitag.json)
            url=$(jq -r ".[$index].url" .github/freitag.json)
          fi
          message="${message//$'\n'/\\n}"
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$message" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "index=$index" >> $GITHUB_ENV

      - name: Update index
        if: github.event_name == 'schedule'
        run: |
          new_index=$((index + 1))
          total_messages=$(jq 'length' .github/freitag.json)
          if [ $new_index -ge $total_messages ]; then
            new_index=0
          fi
          echo $new_index > .github/current_index.txt
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/current_index.txt
          git commit -m "Update current index to $new_index"
          git push

      - name: Send friday reminder
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.channel || 'CQ3EXM36X' }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.read_json.outputs.message }} \n\n ${{ steps.read_json.outputs.url }}"
                  }
                }
              ]
            }
