name: Security
on:
  pull_request:
    branches: [main, master]
jobs:
  gitleaks:
    uses: Techfolk-AS/.github/.github/workflows/reusable-gitleaks.yml@main
  trivy:
    uses: Techfolk-AS/.github/.github/workflows/reusable-trivy.yml@main
